// Typed loader over the committed content export (src/content-export/).
//
// The export is the pinned `learn site export` format: meta.json,
// subjects.json, and one stories-<subject>.json per available subject.
// Today the files are fixtures authored from the real subject repos'
// merged content; once `learn site export` (task t10) lands, the same
// files are regenerated by the exporter and this module needs no change.
//
// Mapping note: culture-guide has no Lesson grouping, so its export maps
// `lessons` to the module's Concept count (documented in the README).

import subjectsJson from "../content-export/subjects.json";
import frenchStories from "../content-export/stories-french.json";
import spanishStories from "../content-export/stories-spanish.json";
import cultureGuideStories from "../content-export/stories-culture-guide.json";

export interface Module {
  id: string;
  title: string;
  summary: string;
  lessons: number;
}

export interface Subject {
  name: string;
  display_name: string;
  description: string;
  repo: string;
  available: boolean;
  modules: Module[];
}

export interface GlossaryEntry {
  term: string;
  definition: string;
  note?: string;
}

// A pick-the-right-word cloze blank: the reader picks `answer` out of
// `options` (distractors + the correct word). See docs/specs/
// subject-plugin-contract.md §3.6.1 (learn-cli's t3 uplift).
export interface ClozeBlank {
  id: string;
  options: string[];
  answer: string;
}

export interface Exercise {
  id: string;
  type: string;
  prompt: string;
  item_id?: string;
  choices?: string[];
  answer?: string;
  rubric?: string;
  // Pick-the-right-word cloze variant ONLY (§3.6.1): the passage with each
  // blank marked `{{blank_id}}`, plus one `blanks[]` entry per placeholder.
  // Absent for the legacy single-blank cloze form (prompt + answer only,
  // unchanged since contract 1.0) and for every non-cloze exercise type.
  text?: string;
  blanks?: ClozeBlank[];
}

export interface Story {
  id: string;
  subject: string;
  title: string;
  level: string;
  level_detail?: string;
  language?: string;
  summary?: string;
  body: string;
  glossary: GlossaryEntry[];
  exercises: Exercise[];
  audio: unknown;
  source?: Record<string, unknown>;
}

interface StoriesFile {
  subject: string;
  stories: Story[];
}

const STORIES: Record<string, StoriesFile> = {
  french: frenchStories as StoriesFile,
  spanish: spanishStories as StoriesFile,
  "culture-guide": cultureGuideStories as StoriesFile,
};

export function getSubjects(): Subject[] {
  return subjectsJson as Subject[];
}

export function getStories(subject: string): Story[] {
  return STORIES[subject]?.stories ?? [];
}

export function storyCount(subject: Subject): number {
  return getStories(subject.name).length;
}

export function moduleCount(subject: Subject): number {
  return subject.modules.length;
}

const LEVEL_ORDER: Record<string, number> = {
  beginner: 0,
  intermediate: 1,
  advanced: 2,
};

export function levelRank(level: string): number {
  return LEVEL_ORDER[level] ?? 99;
}
